global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    scheme: 'http'
    static_configs:
      - targets: ['192.168.2.2:9100']
        labels:
          instance: lab-node
      - targets: ['192.168.2.2:9101']
        labels:
          instance: gateway-node
      - targets: ['192.168.2.2:9102']
        labels:
          instance: banwagon-node
      - targets: ['192.168.2.2:9103']
        labels:
          instance: virmach-node
  - job_name: 'cadvisor'
    scheme: 'http'
    static_configs:
      - targets: ['192.168.2.2:9099']
        labels:
          instance: lab-cadvisor
